export const IPC_CHANNELS = {
  DIALOG_OPEN_SELECT_GIT_REPOSITORY_FOLDER:
    "dialog:openSelectGitRepositoryFolder",
  DIALOG_OPEN_SELECT_PARENT_FOLDER: "dialog:openSelectParentFolder",
  GIT_GET_GLOBAL_CONFIG: "git:getGlobalConfig",
  GIT_SET_GLOBAL_CONFIG: "git:setGlobalConfig",
  GIT_GET_CURRENT_BRANCH: "git:getCurrentBranch",
  GIT_LIST_BRANCHES: "git:listBranches",
  GIT_LIST_REMOTE_BRANCHES: "git:listRemoteBranches",
  GIT_CREATE_BRANCH: "git:createBranch",
  GIT_DELETE_BRANCH: "git:deleteBranch",
  GIT_RENAME_BRANCH: "git:renameBranch",
  GIT_CHECKOUT: "git:checkout",
  GIT_GET_STATUS: "git:getStatus",
  GIT_STAGE_FILE: "git:stageFile",
  GIT_UNSTAGE_FILE: "git:unstageFile",
  GIT_UNSTAGE_ALL_FILES: "git:unstageAllFiles",
  GIT_STAGE_LINES: "git:stageLines",
  GIT_UNSTAGE_LINES: "git:unstageLines",
  GIT_COMMIT: "git:commit",
  GIT_LOG: "git:log",
  GIT_GET_DIFF: "git:getDiff",
  GIT_LIST_STASHES: "git:listStashes",
  GIT_STASH: "git:stash",
  GIT_POP_STASH: "git:popStash",
  GIT_DELETE_STASH: "git:deleteStash",
  GIT_CREATE_REPOSITORY: "git:createRepository",
  GIT_CLONE: "git:clone",
  GIT_GET_REMOTE_URL: "git:getRemoteUrl",
  GIT_FETCH: "git:fetch",
  GIT_PUSH: "git:push",
  GIT_PULL_CURRENT_BRANCH: "git:pullCurrentBranch",
  GIT_PULL_NON_CURRENT_BRANCH: "git:pullNonCurrentBranch",
  SSH_FIND_KEYS: "ssh:findKeys",
  SSH_GENERATE_KEY: "ssh:generateKey",
  SSH_READ_PUBLIC_KEY: "ssh:readPublicKey",
  SSH_IS_HOST_TRUSTED: "ssh:isHostTrusted",
  SSH_TRUST_HOST: "ssh:trustHost",
} as const;
